# Generated by Django 4.2.1 on 2023-05-25 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0006_target_usertargets'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('text', models.CharField(max_length=8092)),
            ],
        ),
        migrations.CreateModel(
            name='NewsPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='news.news')),
                ('preference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to='user.preference')),
            ],
        ),
    ]
