# Generated by Django 4.0.3 on 2023-05-26 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_news_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('background_color', models.CharField(help_text='hex code', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='NewsTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='news.news')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to='news.tag')),
            ],
        ),
    ]
