# Generated by Django 4.0.3 on 2023-06-09 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='address',
            field=models.CharField(blank=True, max_length=2047, null=True),
        ),
        migrations.AddField(
            model_name='point',
            name='phone_number',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='point',
            name='work_time',
            field=models.CharField(blank=True, max_length=2047, null=True),
        ),
    ]
