# Generated by Django 4.0.3 on 2023-06-10 11:52
from random import choice

from django.db import migrations, models
import django.db.models.deletion


def set_random(apps, schema_editor):
    Point = apps.get_model('map', 'Point')
    PointPreference = apps.get_model('map', 'PointPreference')
    Preference = apps.get_model('user', 'Preference')

    points = Point.objects.all()
    preferences = Preference.objects.all()

    for point in points:
        PointPreference.objects.create(
            point=point,
            preference=choice(preferences)
        )


def reverse_random(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_userpreferences_unique_together_and_more'),
        ('map', '0002_point_address_point_phone_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='map.point')),
                ('preference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='user.preference')),
            ],
            options={
                'unique_together': {('point', 'preference')},
            },
        ),
        migrations.RunPython(set_random, reverse_random)
    ]
