# Generated by Django 4.0.3 on 2023-05-27 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='images',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='videos',
        ),
    ]
