# Generated by Django 4.0.3 on 2023-05-28 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_lesson_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='description',
            field=models.TextField(default='Please fill me'),
            preserve_default=False,
        ),
    ]
