# Generated by Django 4.2.1 on 2023-05-25 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='correct_answer_reaction',
            field=models.CharField(blank=True, max_length=2047, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='incorrect_answer_reaction',
            field=models.CharField(blank=True, max_length=2047, null=True),
        ),
    ]
