# Generated by Django 4.0.3 on 2023-05-27 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_alter_useranswers_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='text',
            field=models.TextField(default='Fill me please'),
            preserve_default=False,
        ),
    ]
