# Generated by Django 4.2.1 on 2023-05-25 10:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_managers_remove_user_username_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_last_name_private',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.IntegerField(default=18, validators=[django.core.validators.MinValueValidator(12), django.core.validators.MaxValueValidator(99)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='is_age_private',
            field=models.BooleanField(default=False),
        ),
    ]
