# Generated by Django 4.2.1 on 2023-05-25 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_user_is_last_name_private_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_age_private',
            field=models.BooleanField(default=True),
        ),
    ]
