# Generated by Django 4.2.1 on 2023-05-25 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_is_age_private'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('code', models.CharField(help_text='Name for server', max_length=31, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name for user', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='user.preference')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
