# Generated by Django 4.0.3 on 2023-05-27 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_vk_id_private',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='vk_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
