# Generated by Django 4.0.3 on 2023-05-27 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userpreferences',
            unique_together={('user', 'preference')},
        ),
        migrations.AlterUniqueTogether(
            name='usertargets',
            unique_together={('user', 'target')},
        ),
    ]
