# Generated by Django 4.0.3 on 2023-05-26 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField(unique=True)),
                ('exp', models.PositiveIntegerField()),
                ('description', models.CharField(blank=True, max_length=2047, null=True)),
            ],
        ),
    ]
