# Generated by Django 4.0.3 on 2023-05-26 13:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('levels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_exp', models.PositiveBigIntegerField(default=0)),
                ('current_level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='levels.config')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level', to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
    ]
